In [ ]:
import numpy as np
import math

np.set_printoptions(precision=9)  

In [ ]:
#a=mat([[1,2,3],[4,5,6],[7,8,9]])
#translation
#def tfm(dx,dy):
#scale
#def sc(sx,sy):


#rotation  
#def rotate(theta):

#reflectionx
#def refx():

#def refy():

#shearing
#def shx(a):
#def shy(a):
#def shxy(a,b):
  
#def mat(aa):
  
#def mdot(*a):

In [ ]:
#translation
def ts(dx,dy):
  a=[[1,0,dx],
     [0,1,dy],
     [0,0,1]]
  return np.array(a)

#scale
def sc(sx,sy):
  a=[[sx,0,0],[0,sy,0],[0,0,1]]
  return np.array(a)

#rotation  
def rotate(theta):
  a=[[math.cos(math.radians(theta)),-math.sin(math.radians(theta)),0],
     [math.sin(math.radians(theta)),math.cos(math.radians(theta)),0],
     [0,0,1]]
  return np.array(a)

#reflectionx
def refx():
  a=[[1,0,0],[0,-1,0],[0,0,1]]
  return np.array(a)

def refy():
  a=[[-1,0,0],[0,1,0],[0,0,1]]
  return np.array(a)

#shearing
def shx(a):
 aa=[[1,a,0],[0,1,0],[0,0,1]]
 return np.array(aa)

def shy(a):
  aa=[[1,0,0],[a,1,0],[0,0,1]]
  return np.array(aa)

def shxy(a,b):
  aa=[[1,a,0],[b,1,0],[0,0,1]]
  return np.array(aa)

#def invm(a):
 # return a.transpose() 

def mat(aa):
  return np.array(aa)


def mdot(*a):
  c=a[0]
  for i in range(1,len(a)):
    c=np.dot(c,a[i])
  return c
  
  




In [ ]:
 rotate(100/17.326)

array([[ 0.99493055, -0.10056441,  0.        ],
       [ 0.10056441,  0.99493055,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
t1=ts(20,15)
r=rotate(45)
t2=ts(-20,-15)
mdot(t1,r,t2)

array([[ 0.707106781, -0.707106781, 16.464466094],
       [ 0.707106781,  0.707106781, -9.748737342],
       [ 0.         ,  0.         ,  1.         ]])

In [ ]:
#a=mat([[1,2,3],[4,5,6],[7,8,9]])

#translation
#def ts(dx,dy):

#scale
#def sc(sx,sy):


#rotation  
#def rotate(theta):

#reflectionx
#def refx():

#def refy():

#shearing
#def shx(a):
#def shy(a):
#def shxy(a,b):
  
#def mat(aa):
  
#def mdot(*a):
#p=np.array([[],[],[]])

In [ ]:
# for line equation


m=1
c=3**.5
t=math.degrees(math.atan(m))
t1,t2=ts(0,c),ts(0,-c)

r1,r2=rotate(t),rotate(-t)
rx=refx()
#mc=mdot(mdot(t1,r1),mdot(rx,r2),t2)
a=mdot(t1,r1)
b=mdot(rx,r2)
c=mdot(a,b)
c=mdot(c,t2)
print(c)
p=np.array([[5],[5],[1]])
print(mdot(c,p))

[[ 1.996734618e-16  1.000000000e+00 -1.732050808e+00]
 [ 1.000000000e+00 -1.793803890e-16  1.732050808e+00]
 [ 0.000000000e+00  0.000000000e+00  1.000000000e+00]]
[[3.267949192]
 [6.732050808]
 [1.         ]]


In [ ]:
print(t1)
print(t2)
print(r1)
print(r2)
print(rx)

[[1.          0.          0.         ]
 [0.          1.          1.732050808]
 [0.          0.          1.         ]]
[[ 1.           0.           0.         ]
 [ 0.           1.          -1.732050808]
 [ 0.           0.           1.         ]]
[[ 0.707106781 -0.707106781  0.         ]
 [ 0.707106781  0.707106781  0.         ]
 [ 0.           0.           1.         ]]
[[ 0.707106781  0.707106781  0.         ]
 [-0.707106781  0.707106781  0.         ]
 [ 0.           0.           1.         ]]
[[ 1  0  0]
 [ 0 -1  0]
 [ 0  0  1]]


In [ ]:
origin=(0,0)
x=100
y=17.6326
t1=ts(17.6326+12.3674,5)
t1



array([[ 1.,  0., 30.],
       [ 0.,  1.,  5.],
       [ 0.,  0.,  1.]])

In [ ]:
t2=ts(-(17.6326+12.3674),-5)
t2

array([[  1.,   0., -30.],
       [  0.,   1.,  -5.],
       [  0.,   0.,   1.]])

In [ ]:
t=math.degrees(math.atan(y/x))
t

9.999945503884453

In [ ]:
r=rotate(t)
r

array([[ 0.984807918, -0.173647241,  0.         ],
       [ 0.173647241,  0.984807918,  0.         ],
       [ 0.         ,  0.         ,  1.         ]])

In [ ]:
mdot(t2,r,t1)

array([[ 0.984807918, -0.173647241, -1.32399866 ],
       [ 0.173647241,  0.984807918,  5.13345682 ],
       [ 0.         ,  0.         ,  1.         ]])

In [ ]:
a=np.array([[0,1],[1,0]])
b=np.array([[5],[10]])
np.dot(a,b)


array([[10],
       [ 5]])

In [ ]:
mdot(t1,r,t2)

array([[ 0.984807918, -0.173647241,  1.32399866 ],
       [ 0.173647241,  0.984807918, -5.13345682 ],
       [ 0.         ,  0.         ,  1.         ]])

In [ ]:
rotate(45)

array([[ 0.707106781, -0.707106781,  0.         ],
       [ 0.707106781,  0.707106781,  0.         ],
       [ 0.         ,  0.         ,  1.         ]])

In [ ]:
rotate(-45)

array([[ 0.707106781,  0.707106781,  0.         ],
       [-0.707106781,  0.707106781,  0.         ],
       [ 0.         ,  0.         ,  1.         ]])

In [ ]:
#a=mat([[1,2,3],[4,5,6],[7,8,9]])

#translation
#def ts(dx,dy):

#scale
#def sc(sx,sy):


#rotation  
#def rotate(theta):

#reflectionx
#def refx():

#def refy():

#shearing
#def shx(a):
#def shy(a):
#def shxy(a,b):
  
#def mat(aa):
  
#def mdot(*a):
#p=np.array([[],[],[]])3

#Suppose, a composite transformation is defined as scaling 5 times in X-axis and 7 times
#in Y-axis with respect to point (4, 6). Calculate the composite transformation matrix in
#homogenous form. Then, find the new coordinates of the point (26, 4) after
#transformation.


In [ ]:
a,b=6,9
m=mdot(ts(a,b),sc(10,4),ts(-a,-b))
mdot(m,np.array([[31],[29],[1]]))

array([[256],
       [ 89],
       [  1]])

In [ ]:
p0x, p0y = [int(i) for i in input('p0x, p0y: ').split(", ")]
p1x, p1y = [int(i) for i in input('p1x, p1y: ').split(", ")]

t = float(input('t: '))

pt_help = t * (p1x - p0x), t * (p1y - p0y)
pt = p0x + pt_help[0], p0y + pt_help[1]

mid = round(pt[0] + ((p1x - pt[0]) / 2), 2), round((pt[1] + (p1y - pt[1]) / 2), 2)

print(pt_help)
print(pt)
print(mid)

In [ ]:
mdot(m,np.array([[4],[17],[1]]))

array([[106],
       [258],
       [  1]])

In [ ]:
np.array([[26],[4],[1]])

array([[26],
       [ 4],
       [ 1]])

In [ ]:
mdot(np.array([[-1,0,0],[0,-1,0],[0,0,1]]),ts(4,2))


array([[-1,  0, -4],
       [ 0, -1, -2],
       [ 0,  0,  1]])

In [ ]:
rotate(180)

array([[-1.000000000e+00, -1.224646799e-16,  0.000000000e+00],
       [ 1.224646799e-16, -1.000000000e+00,  0.000000000e+00],
       [ 0.000000000e+00,  0.000000000e+00,  1.000000000e+00]])