In [5]:
import math
import numpy as np
import random

# profit = {'A': 7, 'B': 3, 'C': 12, 'D': 5, 'E': 4, 'F': 16, 'G': 20}
# weight = {'A': 3, 'B': 2, 'C': 6, 'D': 8, 'E': 5, 'F': 1, 'G': 4}

profit = [7, 3, 12, 5, 4, 16, 20]
weight = [3, 2, 6, 8, 5, 1, 4]

def fit_n(chromosomes):
    return [fit(chromosome) for chromosome in chromosomes]

def fit(chromosome):
    p, w = 0, 0
    for i in range(len(chromosome)):
        p += chromosome[i] * profit[i]
        w += chromosome[i] * weight[i]

    if w > 20:
        return 0
    
    return p

def select(chromosomes, fit):
    # a = list(range(len(chromosomes)))

    # total_fit = sum(fit)
    # p = []

    # for f in fit:
        # p.append(f / total_fit)

    #selected = np.random.choice(a, 1, True, p)[0]

    max_fit = max(fit)
    second_max_fit = min(fit)

    for f in fit:
        if f != max_fit and f > second_max_fit:
            second_max_fit = f
    
    max_idx = 0
    while fit[max_idx] != max_fit:
        max_idx += 1
    
    second_max_idx = 0
    while fit[second_max_idx] != second_max_fit:
        second_max_idx += 1
    

    return chromosomes[max_idx], chromosomes[second_max_idx]
    
def crossover(x, y):
    pivot = random.randint(0, len(x) - 1)

    child1 = np.append(x[:pivot], y[pivot:])

    child2 = np.append(y[:pivot], x[pivot:])

    return child1, child2

def mutate(child):
    pointer = random.randint(0, len(child) - 1)
    pointer_value = random.randint(0, 1)

    mutated_child = np.copy(child)

    mutated_child[pointer] = pointer_value

    return mutated_child

population = 4
chromosomes = np.random.randint(0, 2, (population, len(profit)))

sepa = '\n' + '=' * len('Answer for 1.1')

print('Answer for 1.1', sepa)
for chrome in chromosomes:
    print(chrome)

print('\nAnswer for 1.2', sepa)
print('Analyze fit function and write in your own words')

print('\nAnswer for 1.3', sepa)
for chrome in chromosomes:
    print(chrome, '-', fit(chrome))

print('\nAnswer for 1.4', sepa)
# first_parent = select(chromosomes, fit_n(chromosomes))
# second_parent = select(chromosomes, fit_n(chromosomes))
first_parent, second_parent = select(chromosomes, fit_n(chromosomes))

print('First selection:', first_parent)
print('Second selection:', second_parent)

print('\nAnswer for 1.5', sepa)
child1, child2 = crossover(first_parent, second_parent)

print('First child:', child1)
print('Second child:', child2)

print('\nAnswer for 1.6', sepa)
mutation_threshold = 0.4

for child in child1, child2:
    # if random.random() < mutation_threshold:
        print("Mutation:", mutate(child))

# print(sum(profit))

Answer for 1.1 
[0 0 1 0 0 1 1]
[1 0 0 0 0 1 0]
[1 1 0 0 1 1 0]
[1 1 0 0 0 0 0]

Answer for 1.2 
Analyze fit function and write in your own words

Answer for 1.3 
[0 0 1 0 0 1 1] - 48
[1 0 0 0 0 1 0] - 23
[1 1 0 0 1 1 0] - 30
[1 1 0 0 0 0 0] - 10

Answer for 1.4 
First selection: [0 0 1 0 0 1 1]
Second selection: [1 1 0 0 1 1 0]

Answer for 1.5 
First child: [0 0 1 0 0 1 0]
Second child: [1 1 0 0 1 1 1]

Answer for 1.6 
Mutation: [0 0 1 0 0 1 1]
Mutation: [1 1 0 0 1 1 1]


In [6]:
import math
import numpy as np
import random

# profit = {'A': 7, 'B': 3, 'C': 12, 'D': 5, 'E': 4, 'F': 16, 'G': 20}
# weight = {'A': 3, 'B': 2, 'C': 6, 'D': 8, 'E': 5, 'F': 1, 'G': 4}

profit = [7, 3, 12, 5, 4, 16, 20]
weight = [3, 2, 6, 8, 5, 1, 4]

def fit_n(chromosomes):
    return [fit(chromosome) for chromosome in chromosomes]

def fit(chromosome):
    p, w = 0, 0
    for i in range(len(chromosome)):
        p += chromosome[i] * profit[i]
        w += chromosome[i] * weight[i]

    if w > 20:
        return 0
    
    return p

def select(chromosomes, fit):
    # a = list(range(len(chromosomes)))

    # total_fit = sum(fit)
    # p = []

    # for f in fit:
        # p.append(f / total_fit)

    #selected = np.random.choice(a, 1, True, p)[0]

    max_fit = max(fit)
    second_max_fit = min(fit)

    for f in fit:
        if f != max_fit and f > second_max_fit:
            second_max_fit = f
    
    max_idx = 0
    while fit[max_idx] != max_fit:
        max_idx += 1
    
    second_max_idx = 0
    while fit[second_max_idx] != second_max_fit:
        second_max_idx += 1
    

    return chromosomes[max_idx], chromosomes[second_max_idx]
    
def crossover(x, y):
    pivot = random.randint(0, len(x) - 1)

    child1 = np.append(x[:pivot], y[pivot:])

    child2 = np.append(y[:pivot], x[pivot:])

    return child1, child2

def mutate(child):
    pointer = random.randint(0, len(child) - 1)
    pointer_value = random.randint(0, 1)

    mutated_child = np.copy(child)

    mutated_child[pointer] = pointer_value

    return mutated_child

population = 4
chromosomes = np.random.randint(0, 2, (population, len(profit)))

sepa = '\n' + '=' * len('Answer for 1.1')

print('Answer for 1.1', sepa)
for chrome in chromosomes:
    print(chrome)

print('\nAnswer for 1.2', sepa)
print('Analyze fit function and write in your own words')

print('\nAnswer for 1.3', sepa)
for chrome in chromosomes:
    print(chrome, '-', fit(chrome))

print('\nAnswer for 1.4', sepa)
# first_parent = select(chromosomes, fit_n(chromosomes))
# second_parent = select(chromosomes, fit_n(chromosomes))
first_parent, second_parent = select(chromosomes, fit_n(chromosomes))

print('First selection:', first_parent)
print('Second selection:', second_parent)

print('\nAnswer for 1.5', sepa)
child1, child2 = crossover(first_parent, second_parent)

print('First child:', child1)
print('Second child:', child2)

print('\nAnswer for 1.6', sepa)
mutation_threshold = 0.4

for child in child1, child2:
    if random.random() < mutation_threshold:
        print("Mutation:", mutate(child))

# print(sum(profit))

Answer for 1.1 
[1 0 1 0 1 0 0]
[1 1 0 1 1 1 0]
[1 1 0 0 1 0 0]
[1 1 1 0 0 0 0]

Answer for 1.2 
Analyze fit function and write in your own words

Answer for 1.3 
[1 0 1 0 1 0 0] - 23
[1 1 0 1 1 1 0] - 35
[1 1 0 0 1 0 0] - 14
[1 1 1 0 0 0 0] - 22

Answer for 1.4 
First selection: [1 1 0 1 1 1 0]
Second selection: [1 0 1 0 1 0 0]

Answer for 1.5 
First child: [1 1 0 1 1 0 0]
Second child: [1 0 1 0 1 1 0]

Answer for 1.6 
Mutation: [1 1 0 1 1 0 0]
Mutation: [1 1 1 0 1 1 0]


In [7]:
import math
import random
import numpy as np

cost_map = [[math.inf, 2, 4, math.inf, math.inf, math.inf],
            [2, math.inf, 3, 5, math.inf, 15],
            [4, 3, math.inf, 3, 6, 11],
            [math.inf, 5, 3, math.inf, 1, 6],
            [math.inf, math.inf, 6, 1, math.inf, 4],
            [math.inf, 15, 11, 6, 4, math.inf]]

path = [[1, 2],
        [0, 2, 3, 5],
        [0, 1, 3, 4, 5],
        [1, 2, 4, 5],
        [2, 3, 5],
        [1, 2, 3, 4]]

def fitness_population(population):
    return [fitness(chromosome) for chromosome in population]

def fitness(chromosome):
    path_cost = 0

    for i in range(len(chromosome)):
        if chromosome[i] != None:
            path_cost += cost_map[i][chromosome[i]]

    return path_cost

def select(population, fitness, number):
    p = []
    f = []
    for chromosome in population:
        c = []
        for gene in chromosome:
            c.append(gene)
        p.append(c)
    
    for fit in fitness:
        f.append(fit)
    
    selector = []
    for i in range(len(p)):
        selector.append([f[i], p[i]])

    for i in range(len(selector)):
        max_idx = i
        for j in range(i, len(selector)):
            if selector[j][0] > selector[max_idx][0]:
                max_idx = j
        if i != max_idx:
            temp = selector[i]
            selector[i] = selector[max_idx]
            selector[max_idx] = temp
    
    return selector[:number]

def crossover(x, y):
    child = []
    pivot = random.randint(0, len(x) - 1)
    
    for i in range(pivot):
        child.append(x[i])
    
    for i in range(pivot, len(y)):
        child.append(y[i])
    
    return child

def mutate(child):
    idx = random.randint(0, len(child) - 1)
    val = random.randint(0, len(child) - 1)

    child[idx] = val

def fill(chromosome):
    city = [0, 1, 2, 3, 4, 5, None]

    for gene in chromosome:
        city.remove(gene)
    
    idx = 0
    for i in range(len(chromosome)):
        if chromosome[i] == None:
            idx = i
    
    chromosome[idx] = city[0]

def generate_chromosome():
    chromosome = [None, None, None, None, None, None]
    connection = []

    while len(connection) < 6:
        node = random.randint(0, 5)
        while node in connection:
            node = random.randint(0, 5)
        connection.append(node)

    source = connection[0]
    for i in range(1, len(connection) - 1):
        chromosome[source] = connection[i]
        source = connection[i]

    chromosome[connection[-1]] = connection[0]

    fill(chromosome)

    if fitness(chromosome) == math.inf:
        return generate_chromosome()

    # fill(chromosome)
    return chromosome

user_input = None

population = []

for i in range(3):
    population.append(generate_chromosome())

print('Answer for 2.1')
print('=' * 14)
for chromosome in population:
    print(chromosome)


print('\n\nAnswer for 2.2')
print('=' * 14)
print('i.   Gene are each elements of the array. For example, 1, 3, 0, etc.')
print('ii.  The collection of gene is known as chromosome. Therefore, each array represents a chromosome.')


print('\n\nAnswer for 2.3')
print('=' * 14)
print('Explain the above fitness function in your own words.')


print('\n\nAnswer for 2.4')
print('=' * 14)
fitnesses = fitness_population(population)
print('+%20s+%10s+' % ('-' * 20, '-' * 10))
print('|%20s|%10s|' % ('Chromosome', 'Fitness'))
print('+%20s+%10s+' % ('-' * 20, '-' * 10))
for chromosome, fit_value in zip(population, fitnesses):
    print('|%20s|%10s|' % (chromosome, fit_value))
    print('+%20s+%10s+' % ('-' * 20, '-' * 10))

print('\n\nSelected chromosomes:')
selected_chromosome = select(population, fitnesses, 2)

for chromosome in selected_chromosome:
    print('   ', chromosome[1])


print('\n\nAnswer for 2.5')
print('=' * 14)
child = crossover(selected_chromosome[0][1], selected_chromosome[1][1])
print('+%20s+%10s+' % ('-' * 20, '-' * 10))
print('|%20s|%10s|' % ('Child', 'Fitness'))
print('+%20s+%10s+' % ('-' * 20, '-' * 10))
print('|%20s|%10s|' % (child, fitness(child)))
print('+%20s+%10s+' % ('-' * 20, '-' * 10))


print('\n\nAnswer for 2.6')
print('=' * 14)
mutate(child)
print('+%20s+%10s+' % ('-' * 20, '-' * 10))
print('|%20s|%10s|' % ('Child', 'Fitness'))
print('+%20s+%10s+' % ('-' * 20, '-' * 10))
print('|%20s|%10s|' % (child, fitness(child)))
print('+%20s+%10s+' % ('-' * 20, '-' * 10))

Answer for 2.1
[2, 0, 3, 4, 5, 1]
[2, 0, 4, 1, 5, 3]
[2, 0, 4, 5, 3, 1]


Answer for 2.2
i.   Gene are each elements of the array. For example, 1, 3, 0, etc.
ii.  The collection of gene is known as chromosome. Therefore, each array represents a chromosome.


Answer for 2.3
Explain the above fitness function in your own words.


Answer for 2.4
+--------------------+----------+
|          Chromosome|   Fitness|
+--------------------+----------+
|  [2, 0, 3, 4, 5, 1]|        29|
+--------------------+----------+
|  [2, 0, 4, 1, 5, 3]|        27|
+--------------------+----------+
|  [2, 0, 4, 5, 3, 1]|        34|
+--------------------+----------+


Selected chromosomes:
    [2, 0, 4, 5, 3, 1]
    [2, 0, 3, 4, 5, 1]


Answer for 2.5
+--------------------+----------+
|               Child|   Fitness|
+--------------------+----------+
|  [2, 0, 4, 4, 5, 1]|        32|
+--------------------+----------+


Answer for 2.6
+--------------------+----------+
|               Child|   Fitness|
+------

In [8]:
def chromosomes():
  c=[]
  count=0
  while True:
    i=random.randint(0, 6)
    if i not in c:
      c.append(i)
      count+=1
    if count==6:
      break
  return c
chromosomes()



[1, 4, 0, 5, 2, 6]