In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b=np.array([[7.0,8.0,9.0,9.0,4.5],[5.9,8.6,5.4,8.7,4.5]],dtype="int32")
print(b)

[[7 8 9 9 4]
 [5 8 5 8 4]]


In [ ]:
#get dimension
a.ndim

1

In [ ]:
#get dimension
b.ndim

2

In [ ]:
b.shape# tells shape

(2, 5)

In [ ]:
a.shape

(3,)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('int32')

In [ ]:
a.itemsize

8

In [ ]:
b.itemsize

4

In [ ]:
a.size #byte

3

In [ ]:
a=np.array([[1,2,3,4,5],[1,5,9,8,7]])

In [ ]:
a[1,2]

9

In [22]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5])

In [ ]:
#get a specific row
a[1,:]

array([1, 5, 9, 8, 7])

In [ ]:
#get a specific column
a[:,2] 

array([3, 9])